# Generated by Django 5.2.3 on 2025-07-05 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CadreType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "cadre_types",
            },
        ),
        migrations.CreateModel(
            name="ClientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "client_types",
            },
        ),
        migrations.CreateModel(
            name="CommandeStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "commande_status",
            },
        ),
        migrations.CreateModel(
            name="Comportement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "comportements",
            },
        ),
        migrations.CreateModel(
            name="Consommable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_de_peremption", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "consommables",
            },
        ),
        migrations.CreateModel(
            name="ConsommableType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("seuil_alerte", models.IntegerField()),
            ],
            options={
                "db_table": "consommable_types",
            },
        ),
        migrations.CreateModel(
            name="Essaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "essaims",
            },
        ),
        migrations.CreateModel(
            name="EssaimOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "essaim_origins",
            },
        ),
        migrations.CreateModel(
            name="EssaimRace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "essaim_races",
            },
        ),
        migrations.CreateModel(
            name="EssaimStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "essaim_status",
            },
        ),
        migrations.CreateModel(
            name="Hausse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "hausses",
            },
        ),
        migrations.CreateModel(
            name="InterventionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "intervention_type",
            },
        ),
        migrations.CreateModel(
            name="Localization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "localizations",
            },
        ),
        migrations.CreateModel(
            name="LocalizationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "localization_status",
            },
        ),
        migrations.CreateModel(
            name="Materiel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("durre_de_vie_estimee", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "materiels",
            },
        ),
        migrations.CreateModel(
            name="MaterielStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "materiel_status",
            },
        ),
        migrations.CreateModel(
            name="MaterielType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("seuil_alerte", models.IntegerField()),
            ],
            options={
                "db_table": "materiel_types",
            },
        ),
        migrations.CreateModel(
            name="MielType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "miel_types",
            },
        ),
        migrations.CreateModel(
            name="ModePayement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "mode_payements",
            },
        ),
        migrations.CreateModel(
            name="RucheStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "ruche_status",
            },
        ),
        migrations.CreateModel(
            name="TaskPriorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "task_priorites",
            },
        ),
        migrations.CreateModel(
            name="TaskStatusType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "task_status_type",
            },
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "task_types",
            },
        ),
        migrations.CreateModel(
            name="UniteMesure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "unite_mesures",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("note", models.TextField()),
                ("adresse", models.CharField(max_length=255)),
                (
                    "client_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="projet.clienttype",
                    ),
                ),
            ],
            options={
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("livraison_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="projet.client",
                    ),
                ),
            ],
            options={
                "db_table": "commandes",
            },
        ),
        migrations.CreateModel(
            name="CommandeStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commande_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commande_status_histories",
                        to="projet.commande",
                    ),
                ),
                (
                    "commande_status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commande_status_histories",
                        to="projet.commandestatus",
                    ),
                ),
            ],
            options={
                "db_table": "commande_status_histories",
            },
        ),
        migrations.CreateModel(
            name="ConsommableConsomme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consommable_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommable_consomme",
                        to="projet.consommable",
                    ),
                ),
            ],
            options={
                "db_table": "consommable_consomme",
            },
        ),
        migrations.AddField(
            model_name="consommable",
            name="consommable_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommables",
                to="projet.consommabletype",
            ),
        ),
        migrations.CreateModel(
            name="EssaimDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("is_death", models.BooleanField()),
                ("ouvrier_added", models.IntegerField()),
                ("faux_bourdon_added", models.IntegerField()),
                ("reine_added", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essaim_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essaim_details",
                        to="projet.essaim",
                    ),
                ),
            ],
            options={
                "db_table": "essaim_details",
            },
        ),
        migrations.AddField(
            model_name="essaim",
            name="essaim_origin_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essaims",
                to="projet.essaimorigin",
            ),
        ),
        migrations.AddField(
            model_name="essaim",
            name="essaim_race_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="essaims",
                to="projet.essaimrace",
            ),
        ),
        migrations.CreateModel(
            name="EssaimSanteHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "force_colonie",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("egg_present", models.BooleanField()),
                ("couvain_present", models.BooleanField()),
                ("reine_present", models.BooleanField()),
                ("parasite", models.CharField(max_length=255)),
                ("maladie", models.CharField(max_length=255)),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comportement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essaim_sante_histories",
                        to="projet.comportement",
                    ),
                ),
                (
                    "essaim_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essaim_sante_histories",
                        to="projet.essaim",
                    ),
                ),
            ],
            options={
                "db_table": "essaim_sante_histories",
            },
        ),
        migrations.CreateModel(
            name="EssaimStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issaim_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essaim_status_histories",
                        to="projet.essaim",
                    ),
                ),
                (
                    "issaim_status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essaim_status_histories",
                        to="projet.essaimstatus",
                    ),
                ),
            ],
            options={
                "db_table": "essaim_status_histories",
            },
        ),
        migrations.CreateModel(
            name="HausseCadre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_cadre", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hausse_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hausse_cadres",
                        to="projet.hausse",
                    ),
                ),
            ],
            options={
                "db_table": "hausse_cadres",
            },
        ),
        migrations.CreateModel(
            name="HausseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cadre_max_capacity", models.IntegerField()),
                (
                    "cadre_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hausse_types",
                        to="projet.cadretype",
                    ),
                ),
            ],
            options={
                "db_table": "hausse_types",
            },
        ),
        migrations.AddField(
            model_name="hausse",
            name="hausse_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hausses",
                to="projet.haussetype",
            ),
        ),
        migrations.CreateModel(
            name="LocalizationStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "localization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localization_status_histories",
                        to="projet.localization",
                    ),
                ),
                (
                    "localization_status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localization_status_histories",
                        to="projet.localizationstatus",
                    ),
                ),
            ],
            options={
                "db_table": "localization_status_histories",
            },
        ),
        migrations.CreateModel(
            name="MaterielStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "materiel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiel_status_histories",
                        to="projet.materiel",
                    ),
                ),
                (
                    "materiel_status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiel_status_histories",
                        to="projet.materielstatus",
                    ),
                ),
            ],
            options={
                "db_table": "materiel_status_histories",
            },
        ),
        migrations.AddField(
            model_name="materiel",
            name="materiel_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materiels",
                to="projet.materieltype",
            ),
        ),
        migrations.CreateModel(
            name="Miel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite_unite", models.IntegerField()),
                (
                    "consommable_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miels",
                        to="projet.consommabletype",
                    ),
                ),
                (
                    "miel_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miels",
                        to="projet.mieltype",
                    ),
                ),
                (
                    "unite_mesure_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miels",
                        to="projet.unitemesure",
                    ),
                ),
            ],
            options={
                "db_table": "miels",
            },
        ),
        migrations.CreateModel(
            name="CommandeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                (
                    "commande_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commande_details",
                        to="projet.commande",
                    ),
                ),
                (
                    "miel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commande_details",
                        to="projet.miel",
                    ),
                ),
            ],
            options={
                "db_table": "commande_details",
            },
        ),
        migrations.CreateModel(
            name="MielPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "miel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miel_price_histories",
                        to="projet.miel",
                    ),
                ),
            ],
            options={
                "db_table": "miel_price_histories",
            },
        ),
        migrations.CreateModel(
            name="MielStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_quantity", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "miel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miel_stock",
                        to="projet.miel",
                    ),
                ),
            ],
            options={
                "db_table": "miel_stock",
            },
        ),
        migrations.CreateModel(
            name="Ruche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "essaim_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruches",
                        to="projet.essaim",
                    ),
                ),
                (
                    "localizations_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruches",
                        to="projet.localization",
                    ),
                ),
            ],
            options={
                "db_table": "ruches",
            },
        ),
        migrations.CreateModel(
            name="Recolte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poids_miel", models.FloatField()),
                ("taux_humidite", models.FloatField()),
                (
                    "quantite",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ruche_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recoltes",
                        to="projet.ruche",
                    ),
                ),
            ],
            options={
                "db_table": "recoltes",
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("donnees", models.TextField()),
                ("details", models.CharField(max_length=255)),
                ("date_prevue", models.DateField()),
                ("date_realisation", models.DateField()),
                (
                    "intervention_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention",
                        to="projet.interventiontype",
                    ),
                ),
                (
                    "localization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention",
                        to="projet.localization",
                    ),
                ),
                (
                    "ruche_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention",
                        to="projet.ruche",
                    ),
                ),
            ],
            options={
                "db_table": "intervention",
            },
        ),
        migrations.CreateModel(
            name="RucheHausseHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "hausse_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruche_hausse_histories",
                        to="projet.hausse",
                    ),
                ),
                (
                    "ruche_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruche_hausse_histories",
                        to="projet.ruche",
                    ),
                ),
            ],
            options={
                "db_table": "ruche_hausse_histories",
            },
        ),
        migrations.CreateModel(
            name="RucheStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ruche_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruche_status_histories",
                        to="projet.ruche",
                    ),
                ),
                (
                    "ruche_status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruche_status_histories",
                        to="projet.ruchestatus",
                    ),
                ),
            ],
            options={
                "db_table": "ruche_status_histories",
            },
        ),
        migrations.CreateModel(
            name="RucheType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hausse_max_capacity", models.IntegerField()),
                (
                    "hausses_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruche_types",
                        to="projet.haussetype",
                    ),
                ),
            ],
            options={
                "db_table": "ruches_types",
            },
        ),
        migrations.AddField(
            model_name="ruche",
            name="ruche_type_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ruches",
                to="projet.ruchetype",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("date_prevue", models.DateField()),
                ("date_realisation", models.DateField()),
                (
                    "localization_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projet.localization",
                    ),
                ),
                (
                    "ruche_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projet.ruche",
                    ),
                ),
                (
                    "task_priorite_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projet.taskpriorite",
                    ),
                ),
                (
                    "task_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projet.tasktype",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
        migrations.CreateModel(
            name="TaskStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_status_histories",
                        to="projet.task",
                    ),
                ),
                (
                    "task_status_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_status_histories",
                        to="projet.taskstatustype",
                    ),
                ),
            ],
            options={
                "db_table": "task_status_histories",
            },
        ),
        migrations.AddField(
            model_name="consommabletype",
            name="unite_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consommable_types",
                to="projet.unitemesure",
            ),
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventes",
                        to="projet.client",
                    ),
                ),
                (
                    "mode_payement_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ventes",
                        to="projet.modepayement",
                    ),
                ),
            ],
            options={
                "db_table": "ventes",
            },
        ),
        migrations.AddField(
            model_name="commande",
            name="vente_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commandes",
                to="projet.vente",
            ),
        ),
        migrations.CreateModel(
            name="VenteDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                (
                    "miel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vente_details",
                        to="projet.miel",
                    ),
                ),
                (
                    "vente_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vente_details",
                        to="projet.vente",
                    ),
                ),
            ],
            options={
                "db_table": "vente_details",
            },
        ),
    ]
