# Generated by Django 5.2.3 on 2025-07-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recolte",
            old_name="ruche_id",
            new_name="ruche",
        ),
    ]
