# Generated by Django 5.2.3 on 2025-07-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0002_rename_ruche_id_recolte_ruche"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recolte",
            old_name="quantite",
            new_name="qualite",
        ),
    ]
