# Generated by Django 5.2.3 on 2025-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0003_rename_quantite_recolte_qualite"),
    ]

    operations = [
        migrations.AddField(
            model_name="recolte",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
