# Generated by Django 5.2.3 on 2025-07-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0004_recolte_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commande",
            old_name="client_id",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="commande",
            old_name="vente_id",
            new_name="vente",
        ),
    ]
