# Generated by Django 5.2.3 on 2025-07-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0006_rename_client_type_id_client_client_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="essaimstatushistory",
            old_name="issaim",
            new_name="essaim",
        ),
        migrations.RenameField(
            model_name="essaimstatushistory",
            old_name="issaim_status",
            new_name="essaim_status",
        ),
    ]
