# Generated by Django 5.2.3 on 2025-07-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0008_alter_commande_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruche',
            name='essaim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ruches', to='projet.essaim'),
        ),
    ]
