# Generated by Django 5.2.3 on 2025-07-09 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0008_alter_commande_vente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="vente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commande",
                to="projet.vente",
            ),
        ),
    ]
