# Generated by Django 5.2.3 on 2025-07-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0009_alter_commande_vente"),
        ("projet", "0009_alter_ruche_essaim"),
    ]

    operations = []
