# Generated by Django 5.2.3 on 2025-07-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0010_merge_20250709_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervention",
            name="localization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervention",
                to="projet.localization",
            ),
        ),
        migrations.AlterField(
            model_name="intervention",
            name="ruche",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervention",
                to="projet.ruche",
            ),
        ),
    ]
