# Generated by Django 5.2.3 on 2025-07-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0011_alter_intervention_localization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="essaim",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
