# Generated by Django 5.2.3 on 2025-07-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0012_essaim_description"),
        ("projet", "0012_intervention_prix_service"),
    ]

    operations = []
