# Generated by Django 5.2.3 on 2025-07-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0013_merge_20250709_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='nb',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PrixMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_materiel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_materiels', to='projet.materiel')),
            ],
            options={
                'db_table': 'prix_materiel',
            },
        ),
    ]
