# Generated by Django 5.2.3 on 2025-07-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projet", "0013_merge_20250709_2102"),
        ("projet", "0014_materiel_nb_prixmateriel"),
    ]

    operations = []
